# Configure main menu and social menu
[[main]]
identifier = "github"
name = "Github"
url = "https://github.com/wira"

[main.params]
icon = "brand-github"
newtab = true

# [[social]]
# identifier = "github"
# name = "GitHub"
# url = "https://github.com/wira"

# [social.params]
# icon = "brand-github"
